# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3d0e537f8b0cdb77d65cfa13e76a7eada640561836a2e67dd87343cf80107a4596727a04de34fcf35d1b41771706d4f57e0ba1b954b068716cbc402b0786f51

test:
  secret_key_base: 91b1d3eda550cd1545a04ff94c99ceec3628ebe436e8a40d665baed0eb18f9df8216dd8fcb0b0d5901de03f35c97a30ec4e9f1e848a8b302c9d7b813c5fc135e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
